Breakfast:
  Idli: 10
  Vada: 10
  Dosa: 20
  Bath: 20
Lunch:
  NorthIndian: 60
  SouthIndian: 55
Snacks:
  PaniPuri:   15
  MasalaPuri: 15
Dinner:
  Friedrice: 65
  Biriyani:  80
Chinese:
  Fried Rice: 65
Soft Drinks:
  Coke: 20
Fruit Juices:
  Apple: 30
Desserts:
  Vanilla: 60
Meals:
  North Indian Thaali: 120
Specials:
  Hotel Specials: 150
